# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ada4a060f7f7f14446cdd0d3127c98ce8974be17e9a7aa2709b463adad4b68e52465fbe527e4f8b94033eba43a4375e299414f92a51fb2c4f78c3c88c30271e

test:
  secret_key_base: fa97ad0ddd1501d439648103dc8e25055c21836a90f4b0b13198f1929b05ac657a880d5c821e26231e7de09ceb430bd280371c5a5cfbdb73d130cbe8090fb2a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
